// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to Wren
class WrenBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WrenBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WrenBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int __ctype_get_mb_cur_max() {
    return ___ctype_get_mb_cur_max();
  }

  late final ___ctype_get_mb_cur_max_ptr =
      _lookup<ffi.NativeFunction<_c___ctype_get_mb_cur_max>>(
          '__ctype_get_mb_cur_max');
  late final _dart___ctype_get_mb_cur_max ___ctype_get_mb_cur_max =
      ___ctype_get_mb_cur_max_ptr.asFunction<_dart___ctype_get_mb_cur_max>();

  double atof(
    ffi.Pointer<ffi.Int8> __nptr,
  ) {
    return _atof(
      __nptr,
    );
  }

  late final _atof_ptr = _lookup<ffi.NativeFunction<_c_atof>>('atof');
  late final _dart_atof _atof = _atof_ptr.asFunction<_dart_atof>();

  int atoi(
    ffi.Pointer<ffi.Int8> __nptr,
  ) {
    return _atoi(
      __nptr,
    );
  }

  late final _atoi_ptr = _lookup<ffi.NativeFunction<_c_atoi>>('atoi');
  late final _dart_atoi _atoi = _atoi_ptr.asFunction<_dart_atoi>();

  int atol(
    ffi.Pointer<ffi.Int8> __nptr,
  ) {
    return _atol(
      __nptr,
    );
  }

  late final _atol_ptr = _lookup<ffi.NativeFunction<_c_atol>>('atol');
  late final _dart_atol _atol = _atol_ptr.asFunction<_dart_atol>();

  int atoll(
    ffi.Pointer<ffi.Int8> __nptr,
  ) {
    return _atoll(
      __nptr,
    );
  }

  late final _atoll_ptr = _lookup<ffi.NativeFunction<_c_atoll>>('atoll');
  late final _dart_atoll _atoll = _atoll_ptr.asFunction<_dart_atoll>();

  double strtod(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ) {
    return _strtod(
      __nptr,
      __endptr,
    );
  }

  late final _strtod_ptr = _lookup<ffi.NativeFunction<_c_strtod>>('strtod');
  late final _dart_strtod _strtod = _strtod_ptr.asFunction<_dart_strtod>();

  double strtof(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ) {
    return _strtof(
      __nptr,
      __endptr,
    );
  }

  late final _strtof_ptr = _lookup<ffi.NativeFunction<_c_strtof>>('strtof');
  late final _dart_strtof _strtof = _strtof_ptr.asFunction<_dart_strtof>();

  int strtol(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtol(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtol_ptr = _lookup<ffi.NativeFunction<_c_strtol>>('strtol');
  late final _dart_strtol _strtol = _strtol_ptr.asFunction<_dart_strtol>();

  int strtoul(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtoul(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoul_ptr = _lookup<ffi.NativeFunction<_c_strtoul>>('strtoul');
  late final _dart_strtoul _strtoul = _strtoul_ptr.asFunction<_dart_strtoul>();

  int strtoq(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtoq(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoq_ptr = _lookup<ffi.NativeFunction<_c_strtoq>>('strtoq');
  late final _dart_strtoq _strtoq = _strtoq_ptr.asFunction<_dart_strtoq>();

  int strtouq(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtouq(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtouq_ptr = _lookup<ffi.NativeFunction<_c_strtouq>>('strtouq');
  late final _dart_strtouq _strtouq = _strtouq_ptr.asFunction<_dart_strtouq>();

  int strtoll(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtoll(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoll_ptr = _lookup<ffi.NativeFunction<_c_strtoll>>('strtoll');
  late final _dart_strtoll _strtoll = _strtoll_ptr.asFunction<_dart_strtoll>();

  int strtoull(
    ffi.Pointer<ffi.Int8> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    return _strtoull(
      __nptr,
      __endptr,
      __base,
    );
  }

  late final _strtoull_ptr =
      _lookup<ffi.NativeFunction<_c_strtoull>>('strtoull');
  late final _dart_strtoull _strtoull =
      _strtoull_ptr.asFunction<_dart_strtoull>();

  ffi.Pointer<ffi.Int8> l64a(
    int __n,
  ) {
    return _l64a(
      __n,
    );
  }

  late final _l64a_ptr = _lookup<ffi.NativeFunction<_c_l64a>>('l64a');
  late final _dart_l64a _l64a = _l64a_ptr.asFunction<_dart_l64a>();

  int a64l(
    ffi.Pointer<ffi.Int8> __s,
  ) {
    return _a64l(
      __s,
    );
  }

  late final _a64l_ptr = _lookup<ffi.NativeFunction<_c_a64l>>('a64l');
  late final _dart_a64l _a64l = _a64l_ptr.asFunction<_dart_a64l>();

  int select(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timeval> __timeout,
  ) {
    return _select(
      __nfds,
      __readfds,
      __writefds,
      __exceptfds,
      __timeout,
    );
  }

  late final _select_ptr = _lookup<ffi.NativeFunction<_c_select>>('select');
  late final _dart_select _select = _select_ptr.asFunction<_dart_select>();

  int pselect(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timespec> __timeout,
    ffi.Pointer<__sigset_t> __sigmask,
  ) {
    return _pselect(
      __nfds,
      __readfds,
      __writefds,
      __exceptfds,
      __timeout,
      __sigmask,
    );
  }

  late final _pselect_ptr = _lookup<ffi.NativeFunction<_c_pselect>>('pselect');
  late final _dart_pselect _pselect = _pselect_ptr.asFunction<_dart_pselect>();

  int random() {
    return _random();
  }

  late final _random_ptr = _lookup<ffi.NativeFunction<_c_random>>('random');
  late final _dart_random _random = _random_ptr.asFunction<_dart_random>();

  void srandom(
    int __seed,
  ) {
    return _srandom(
      __seed,
    );
  }

  late final _srandom_ptr = _lookup<ffi.NativeFunction<_c_srandom>>('srandom');
  late final _dart_srandom _srandom = _srandom_ptr.asFunction<_dart_srandom>();

  ffi.Pointer<ffi.Int8> initstate(
    int __seed,
    ffi.Pointer<ffi.Int8> __statebuf,
    int __statelen,
  ) {
    return _initstate(
      __seed,
      __statebuf,
      __statelen,
    );
  }

  late final _initstate_ptr =
      _lookup<ffi.NativeFunction<_c_initstate>>('initstate');
  late final _dart_initstate _initstate =
      _initstate_ptr.asFunction<_dart_initstate>();

  ffi.Pointer<ffi.Int8> setstate(
    ffi.Pointer<ffi.Int8> __statebuf,
  ) {
    return _setstate(
      __statebuf,
    );
  }

  late final _setstate_ptr =
      _lookup<ffi.NativeFunction<_c_setstate>>('setstate');
  late final _dart_setstate _setstate =
      _setstate_ptr.asFunction<_dart_setstate>();

  int random_r(
    ffi.Pointer<random_data> __buf,
    ffi.Pointer<ffi.Int32> __result,
  ) {
    return _random_r(
      __buf,
      __result,
    );
  }

  late final _random_r_ptr =
      _lookup<ffi.NativeFunction<_c_random_r>>('random_r');
  late final _dart_random_r _random_r =
      _random_r_ptr.asFunction<_dart_random_r>();

  int srandom_r(
    int __seed,
    ffi.Pointer<random_data> __buf,
  ) {
    return _srandom_r(
      __seed,
      __buf,
    );
  }

  late final _srandom_r_ptr =
      _lookup<ffi.NativeFunction<_c_srandom_r>>('srandom_r');
  late final _dart_srandom_r _srandom_r =
      _srandom_r_ptr.asFunction<_dart_srandom_r>();

  int initstate_r(
    int __seed,
    ffi.Pointer<ffi.Int8> __statebuf,
    int __statelen,
    ffi.Pointer<random_data> __buf,
  ) {
    return _initstate_r(
      __seed,
      __statebuf,
      __statelen,
      __buf,
    );
  }

  late final _initstate_r_ptr =
      _lookup<ffi.NativeFunction<_c_initstate_r>>('initstate_r');
  late final _dart_initstate_r _initstate_r =
      _initstate_r_ptr.asFunction<_dart_initstate_r>();

  int setstate_r(
    ffi.Pointer<ffi.Int8> __statebuf,
    ffi.Pointer<random_data> __buf,
  ) {
    return _setstate_r(
      __statebuf,
      __buf,
    );
  }

  late final _setstate_r_ptr =
      _lookup<ffi.NativeFunction<_c_setstate_r>>('setstate_r');
  late final _dart_setstate_r _setstate_r =
      _setstate_r_ptr.asFunction<_dart_setstate_r>();

  int rand() {
    return _rand();
  }

  late final _rand_ptr = _lookup<ffi.NativeFunction<_c_rand>>('rand');
  late final _dart_rand _rand = _rand_ptr.asFunction<_dart_rand>();

  void srand(
    int __seed,
  ) {
    return _srand(
      __seed,
    );
  }

  late final _srand_ptr = _lookup<ffi.NativeFunction<_c_srand>>('srand');
  late final _dart_srand _srand = _srand_ptr.asFunction<_dart_srand>();

  int rand_r(
    ffi.Pointer<ffi.Uint32> __seed,
  ) {
    return _rand_r(
      __seed,
    );
  }

  late final _rand_r_ptr = _lookup<ffi.NativeFunction<_c_rand_r>>('rand_r');
  late final _dart_rand_r _rand_r = _rand_r_ptr.asFunction<_dart_rand_r>();

  double drand48() {
    return _drand48();
  }

  late final _drand48_ptr = _lookup<ffi.NativeFunction<_c_drand48>>('drand48');
  late final _dart_drand48 _drand48 = _drand48_ptr.asFunction<_dart_drand48>();

  double erand48(
    ffi.Pointer<ffi.Uint16> __xsubi,
  ) {
    return _erand48(
      __xsubi,
    );
  }

  late final _erand48_ptr = _lookup<ffi.NativeFunction<_c_erand48>>('erand48');
  late final _dart_erand48 _erand48 = _erand48_ptr.asFunction<_dart_erand48>();

  int lrand48() {
    return _lrand48();
  }

  late final _lrand48_ptr = _lookup<ffi.NativeFunction<_c_lrand48>>('lrand48');
  late final _dart_lrand48 _lrand48 = _lrand48_ptr.asFunction<_dart_lrand48>();

  int nrand48(
    ffi.Pointer<ffi.Uint16> __xsubi,
  ) {
    return _nrand48(
      __xsubi,
    );
  }

  late final _nrand48_ptr = _lookup<ffi.NativeFunction<_c_nrand48>>('nrand48');
  late final _dart_nrand48 _nrand48 = _nrand48_ptr.asFunction<_dart_nrand48>();

  int mrand48() {
    return _mrand48();
  }

  late final _mrand48_ptr = _lookup<ffi.NativeFunction<_c_mrand48>>('mrand48');
  late final _dart_mrand48 _mrand48 = _mrand48_ptr.asFunction<_dart_mrand48>();

  int jrand48(
    ffi.Pointer<ffi.Uint16> __xsubi,
  ) {
    return _jrand48(
      __xsubi,
    );
  }

  late final _jrand48_ptr = _lookup<ffi.NativeFunction<_c_jrand48>>('jrand48');
  late final _dart_jrand48 _jrand48 = _jrand48_ptr.asFunction<_dart_jrand48>();

  void srand48(
    int __seedval,
  ) {
    return _srand48(
      __seedval,
    );
  }

  late final _srand48_ptr = _lookup<ffi.NativeFunction<_c_srand48>>('srand48');
  late final _dart_srand48 _srand48 = _srand48_ptr.asFunction<_dart_srand48>();

  ffi.Pointer<ffi.Uint16> seed48(
    ffi.Pointer<ffi.Uint16> __seed16v,
  ) {
    return _seed48(
      __seed16v,
    );
  }

  late final _seed48_ptr = _lookup<ffi.NativeFunction<_c_seed48>>('seed48');
  late final _dart_seed48 _seed48 = _seed48_ptr.asFunction<_dart_seed48>();

  void lcong48(
    ffi.Pointer<ffi.Uint16> __param,
  ) {
    return _lcong48(
      __param,
    );
  }

  late final _lcong48_ptr = _lookup<ffi.NativeFunction<_c_lcong48>>('lcong48');
  late final _dart_lcong48 _lcong48 = _lcong48_ptr.asFunction<_dart_lcong48>();

  int drand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Double> __result,
  ) {
    return _drand48_r(
      __buffer,
      __result,
    );
  }

  late final _drand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_drand48_r>>('drand48_r');
  late final _dart_drand48_r _drand48_r =
      _drand48_r_ptr.asFunction<_dart_drand48_r>();

  int erand48_r(
    ffi.Pointer<ffi.Uint16> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Double> __result,
  ) {
    return _erand48_r(
      __xsubi,
      __buffer,
      __result,
    );
  }

  late final _erand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_erand48_r>>('erand48_r');
  late final _dart_erand48_r _erand48_r =
      _erand48_r_ptr.asFunction<_dart_erand48_r>();

  int lrand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Int64> __result,
  ) {
    return _lrand48_r(
      __buffer,
      __result,
    );
  }

  late final _lrand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_lrand48_r>>('lrand48_r');
  late final _dart_lrand48_r _lrand48_r =
      _lrand48_r_ptr.asFunction<_dart_lrand48_r>();

  int nrand48_r(
    ffi.Pointer<ffi.Uint16> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Int64> __result,
  ) {
    return _nrand48_r(
      __xsubi,
      __buffer,
      __result,
    );
  }

  late final _nrand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_nrand48_r>>('nrand48_r');
  late final _dart_nrand48_r _nrand48_r =
      _nrand48_r_ptr.asFunction<_dart_nrand48_r>();

  int mrand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Int64> __result,
  ) {
    return _mrand48_r(
      __buffer,
      __result,
    );
  }

  late final _mrand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_mrand48_r>>('mrand48_r');
  late final _dart_mrand48_r _mrand48_r =
      _mrand48_r_ptr.asFunction<_dart_mrand48_r>();

  int jrand48_r(
    ffi.Pointer<ffi.Uint16> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Int64> __result,
  ) {
    return _jrand48_r(
      __xsubi,
      __buffer,
      __result,
    );
  }

  late final _jrand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_jrand48_r>>('jrand48_r');
  late final _dart_jrand48_r _jrand48_r =
      _jrand48_r_ptr.asFunction<_dart_jrand48_r>();

  int srand48_r(
    int __seedval,
    ffi.Pointer<drand48_data> __buffer,
  ) {
    return _srand48_r(
      __seedval,
      __buffer,
    );
  }

  late final _srand48_r_ptr =
      _lookup<ffi.NativeFunction<_c_srand48_r>>('srand48_r');
  late final _dart_srand48_r _srand48_r =
      _srand48_r_ptr.asFunction<_dart_srand48_r>();

  int seed48_r(
    ffi.Pointer<ffi.Uint16> __seed16v,
    ffi.Pointer<drand48_data> __buffer,
  ) {
    return _seed48_r(
      __seed16v,
      __buffer,
    );
  }

  late final _seed48_r_ptr =
      _lookup<ffi.NativeFunction<_c_seed48_r>>('seed48_r');
  late final _dart_seed48_r _seed48_r =
      _seed48_r_ptr.asFunction<_dart_seed48_r>();

  int lcong48_r(
    ffi.Pointer<ffi.Uint16> __param,
    ffi.Pointer<drand48_data> __buffer,
  ) {
    return _lcong48_r(
      __param,
      __buffer,
    );
  }

  late final _lcong48_r_ptr =
      _lookup<ffi.NativeFunction<_c_lcong48_r>>('lcong48_r');
  late final _dart_lcong48_r _lcong48_r =
      _lcong48_r_ptr.asFunction<_dart_lcong48_r>();

  ffi.Pointer<ffi.Void> malloc(
    int __size,
  ) {
    return _malloc(
      __size,
    );
  }

  late final _malloc_ptr = _lookup<ffi.NativeFunction<_c_malloc>>('malloc');
  late final _dart_malloc _malloc = _malloc_ptr.asFunction<_dart_malloc>();

  ffi.Pointer<ffi.Void> calloc(
    int __nmemb,
    int __size,
  ) {
    return _calloc(
      __nmemb,
      __size,
    );
  }

  late final _calloc_ptr = _lookup<ffi.NativeFunction<_c_calloc>>('calloc');
  late final _dart_calloc _calloc = _calloc_ptr.asFunction<_dart_calloc>();

  ffi.Pointer<ffi.Void> realloc(
    ffi.Pointer<ffi.Void> __ptr,
    int __size,
  ) {
    return _realloc(
      __ptr,
      __size,
    );
  }

  late final _realloc_ptr = _lookup<ffi.NativeFunction<_c_realloc>>('realloc');
  late final _dart_realloc _realloc = _realloc_ptr.asFunction<_dart_realloc>();

  ffi.Pointer<ffi.Void> reallocarray(
    ffi.Pointer<ffi.Void> __ptr,
    int __nmemb,
    int __size,
  ) {
    return _reallocarray(
      __ptr,
      __nmemb,
      __size,
    );
  }

  late final _reallocarray_ptr =
      _lookup<ffi.NativeFunction<_c_reallocarray>>('reallocarray');
  late final _dart_reallocarray _reallocarray =
      _reallocarray_ptr.asFunction<_dart_reallocarray>();

  void free(
    ffi.Pointer<ffi.Void> __ptr,
  ) {
    return _free(
      __ptr,
    );
  }

  late final _free_ptr = _lookup<ffi.NativeFunction<_c_free>>('free');
  late final _dart_free _free = _free_ptr.asFunction<_dart_free>();

  ffi.Pointer<ffi.Void> alloca(
    int __size,
  ) {
    return _alloca(
      __size,
    );
  }

  late final _alloca_ptr = _lookup<ffi.NativeFunction<_c_alloca>>('alloca');
  late final _dart_alloca _alloca = _alloca_ptr.asFunction<_dart_alloca>();

  ffi.Pointer<ffi.Void> valloc(
    int __size,
  ) {
    return _valloc(
      __size,
    );
  }

  late final _valloc_ptr = _lookup<ffi.NativeFunction<_c_valloc>>('valloc');
  late final _dart_valloc _valloc = _valloc_ptr.asFunction<_dart_valloc>();

  int posix_memalign(
    ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
    int __alignment,
    int __size,
  ) {
    return _posix_memalign(
      __memptr,
      __alignment,
      __size,
    );
  }

  late final _posix_memalign_ptr =
      _lookup<ffi.NativeFunction<_c_posix_memalign>>('posix_memalign');
  late final _dart_posix_memalign _posix_memalign =
      _posix_memalign_ptr.asFunction<_dart_posix_memalign>();

  ffi.Pointer<ffi.Void> aligned_alloc(
    int __alignment,
    int __size,
  ) {
    return _aligned_alloc(
      __alignment,
      __size,
    );
  }

  late final _aligned_alloc_ptr =
      _lookup<ffi.NativeFunction<_c_aligned_alloc>>('aligned_alloc');
  late final _dart_aligned_alloc _aligned_alloc =
      _aligned_alloc_ptr.asFunction<_dart_aligned_alloc>();

  void abort() {
    return _abort();
  }

  late final _abort_ptr = _lookup<ffi.NativeFunction<_c_abort>>('abort');
  late final _dart_abort _abort = _abort_ptr.asFunction<_dart_abort>();

  int atexit(
    ffi.Pointer<ffi.NativeFunction<_typedefC_1>> __func,
  ) {
    return _atexit(
      __func,
    );
  }

  late final _atexit_ptr = _lookup<ffi.NativeFunction<_c_atexit>>('atexit');
  late final _dart_atexit _atexit = _atexit_ptr.asFunction<_dart_atexit>();

  int at_quick_exit(
    ffi.Pointer<ffi.NativeFunction<_typedefC_2>> __func,
  ) {
    return _at_quick_exit(
      __func,
    );
  }

  late final _at_quick_exit_ptr =
      _lookup<ffi.NativeFunction<_c_at_quick_exit>>('at_quick_exit');
  late final _dart_at_quick_exit _at_quick_exit =
      _at_quick_exit_ptr.asFunction<_dart_at_quick_exit>();

  int on_exit(
    ffi.Pointer<ffi.NativeFunction<_typedefC_3>> __func,
    ffi.Pointer<ffi.Void> __arg,
  ) {
    return _on_exit(
      __func,
      __arg,
    );
  }

  late final _on_exit_ptr = _lookup<ffi.NativeFunction<_c_on_exit>>('on_exit');
  late final _dart_on_exit _on_exit = _on_exit_ptr.asFunction<_dart_on_exit>();

  void exit(
    int __status,
  ) {
    return _exit(
      __status,
    );
  }

  late final _exit_ptr = _lookup<ffi.NativeFunction<_c_exit>>('exit');
  late final _dart_exit _exit = _exit_ptr.asFunction<_dart_exit>();

  void quick_exit(
    int __status,
  ) {
    return _quick_exit(
      __status,
    );
  }

  late final _quick_exit_ptr =
      _lookup<ffi.NativeFunction<_c_quick_exit>>('quick_exit');
  late final _dart_quick_exit _quick_exit =
      _quick_exit_ptr.asFunction<_dart_quick_exit>();

  void _Exit(
    int __status,
  ) {
    return __Exit(
      __status,
    );
  }

  late final __Exit_ptr = _lookup<ffi.NativeFunction<_c__Exit>>('_Exit');
  late final _dart__Exit __Exit = __Exit_ptr.asFunction<_dart__Exit>();

  ffi.Pointer<ffi.Int8> getenv(
    ffi.Pointer<ffi.Int8> __name,
  ) {
    return _getenv(
      __name,
    );
  }

  late final _getenv_ptr = _lookup<ffi.NativeFunction<_c_getenv>>('getenv');
  late final _dart_getenv _getenv = _getenv_ptr.asFunction<_dart_getenv>();

  int putenv(
    ffi.Pointer<ffi.Int8> __string,
  ) {
    return _putenv(
      __string,
    );
  }

  late final _putenv_ptr = _lookup<ffi.NativeFunction<_c_putenv>>('putenv');
  late final _dart_putenv _putenv = _putenv_ptr.asFunction<_dart_putenv>();

  int setenv(
    ffi.Pointer<ffi.Int8> __name,
    ffi.Pointer<ffi.Int8> __value,
    int __replace,
  ) {
    return _setenv(
      __name,
      __value,
      __replace,
    );
  }

  late final _setenv_ptr = _lookup<ffi.NativeFunction<_c_setenv>>('setenv');
  late final _dart_setenv _setenv = _setenv_ptr.asFunction<_dart_setenv>();

  int unsetenv(
    ffi.Pointer<ffi.Int8> __name,
  ) {
    return _unsetenv(
      __name,
    );
  }

  late final _unsetenv_ptr =
      _lookup<ffi.NativeFunction<_c_unsetenv>>('unsetenv');
  late final _dart_unsetenv _unsetenv =
      _unsetenv_ptr.asFunction<_dart_unsetenv>();

  int clearenv() {
    return _clearenv();
  }

  late final _clearenv_ptr =
      _lookup<ffi.NativeFunction<_c_clearenv>>('clearenv');
  late final _dart_clearenv _clearenv =
      _clearenv_ptr.asFunction<_dart_clearenv>();

  ffi.Pointer<ffi.Int8> mktemp(
    ffi.Pointer<ffi.Int8> __template,
  ) {
    return _mktemp(
      __template,
    );
  }

  late final _mktemp_ptr = _lookup<ffi.NativeFunction<_c_mktemp>>('mktemp');
  late final _dart_mktemp _mktemp = _mktemp_ptr.asFunction<_dart_mktemp>();

  int mkstemp(
    ffi.Pointer<ffi.Int8> __template,
  ) {
    return _mkstemp(
      __template,
    );
  }

  late final _mkstemp_ptr = _lookup<ffi.NativeFunction<_c_mkstemp>>('mkstemp');
  late final _dart_mkstemp _mkstemp = _mkstemp_ptr.asFunction<_dart_mkstemp>();

  int mkstemps(
    ffi.Pointer<ffi.Int8> __template,
    int __suffixlen,
  ) {
    return _mkstemps(
      __template,
      __suffixlen,
    );
  }

  late final _mkstemps_ptr =
      _lookup<ffi.NativeFunction<_c_mkstemps>>('mkstemps');
  late final _dart_mkstemps _mkstemps =
      _mkstemps_ptr.asFunction<_dart_mkstemps>();

  ffi.Pointer<ffi.Int8> mkdtemp(
    ffi.Pointer<ffi.Int8> __template,
  ) {
    return _mkdtemp(
      __template,
    );
  }

  late final _mkdtemp_ptr = _lookup<ffi.NativeFunction<_c_mkdtemp>>('mkdtemp');
  late final _dart_mkdtemp _mkdtemp = _mkdtemp_ptr.asFunction<_dart_mkdtemp>();

  int system(
    ffi.Pointer<ffi.Int8> __command,
  ) {
    return _system(
      __command,
    );
  }

  late final _system_ptr = _lookup<ffi.NativeFunction<_c_system>>('system');
  late final _dart_system _system = _system_ptr.asFunction<_dart_system>();

  ffi.Pointer<ffi.Int8> realpath(
    ffi.Pointer<ffi.Int8> __name,
    ffi.Pointer<ffi.Int8> __resolved,
  ) {
    return _realpath(
      __name,
      __resolved,
    );
  }

  late final _realpath_ptr =
      _lookup<ffi.NativeFunction<_c_realpath>>('realpath');
  late final _dart_realpath _realpath =
      _realpath_ptr.asFunction<_dart_realpath>();

  ffi.Pointer<ffi.Void> bsearch(
    ffi.Pointer<ffi.Void> __key,
    ffi.Pointer<ffi.Void> __base,
    int __nmemb,
    int __size,
    ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
  ) {
    return _bsearch(
      __key,
      __base,
      __nmemb,
      __size,
      __compar,
    );
  }

  late final _bsearch_ptr = _lookup<ffi.NativeFunction<_c_bsearch>>('bsearch');
  late final _dart_bsearch _bsearch = _bsearch_ptr.asFunction<_dart_bsearch>();

  void qsort(
    ffi.Pointer<ffi.Void> __base,
    int __nmemb,
    int __size,
    ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
  ) {
    return _qsort(
      __base,
      __nmemb,
      __size,
      __compar,
    );
  }

  late final _qsort_ptr = _lookup<ffi.NativeFunction<_c_qsort>>('qsort');
  late final _dart_qsort _qsort = _qsort_ptr.asFunction<_dart_qsort>();

  int abs(
    int __x,
  ) {
    return _abs(
      __x,
    );
  }

  late final _abs_ptr = _lookup<ffi.NativeFunction<_c_abs>>('abs');
  late final _dart_abs _abs = _abs_ptr.asFunction<_dart_abs>();

  int labs(
    int __x,
  ) {
    return _labs(
      __x,
    );
  }

  late final _labs_ptr = _lookup<ffi.NativeFunction<_c_labs>>('labs');
  late final _dart_labs _labs = _labs_ptr.asFunction<_dart_labs>();

  int llabs(
    int __x,
  ) {
    return _llabs(
      __x,
    );
  }

  late final _llabs_ptr = _lookup<ffi.NativeFunction<_c_llabs>>('llabs');
  late final _dart_llabs _llabs = _llabs_ptr.asFunction<_dart_llabs>();

  div_t div(
    int __numer,
    int __denom,
  ) {
    return _div(
      __numer,
      __denom,
    );
  }

  late final _div_ptr = _lookup<ffi.NativeFunction<_c_div>>('div');
  late final _dart_div _div = _div_ptr.asFunction<_dart_div>();

  ldiv_t ldiv(
    int __numer,
    int __denom,
  ) {
    return _ldiv(
      __numer,
      __denom,
    );
  }

  late final _ldiv_ptr = _lookup<ffi.NativeFunction<_c_ldiv>>('ldiv');
  late final _dart_ldiv _ldiv = _ldiv_ptr.asFunction<_dart_ldiv>();

  lldiv_t lldiv(
    int __numer,
    int __denom,
  ) {
    return _lldiv(
      __numer,
      __denom,
    );
  }

  late final _lldiv_ptr = _lookup<ffi.NativeFunction<_c_lldiv>>('lldiv');
  late final _dart_lldiv _lldiv = _lldiv_ptr.asFunction<_dart_lldiv>();

  ffi.Pointer<ffi.Int8> ecvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int32> __decpt,
    ffi.Pointer<ffi.Int32> __sign,
  ) {
    return _ecvt(
      __value,
      __ndigit,
      __decpt,
      __sign,
    );
  }

  late final _ecvt_ptr = _lookup<ffi.NativeFunction<_c_ecvt>>('ecvt');
  late final _dart_ecvt _ecvt = _ecvt_ptr.asFunction<_dart_ecvt>();

  ffi.Pointer<ffi.Int8> fcvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int32> __decpt,
    ffi.Pointer<ffi.Int32> __sign,
  ) {
    return _fcvt(
      __value,
      __ndigit,
      __decpt,
      __sign,
    );
  }

  late final _fcvt_ptr = _lookup<ffi.NativeFunction<_c_fcvt>>('fcvt');
  late final _dart_fcvt _fcvt = _fcvt_ptr.asFunction<_dart_fcvt>();

  ffi.Pointer<ffi.Int8> gcvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int8> __buf,
  ) {
    return _gcvt(
      __value,
      __ndigit,
      __buf,
    );
  }

  late final _gcvt_ptr = _lookup<ffi.NativeFunction<_c_gcvt>>('gcvt');
  late final _dart_gcvt _gcvt = _gcvt_ptr.asFunction<_dart_gcvt>();

  int ecvt_r(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int32> __decpt,
    ffi.Pointer<ffi.Int32> __sign,
    ffi.Pointer<ffi.Int8> __buf,
    int __len,
  ) {
    return _ecvt_r(
      __value,
      __ndigit,
      __decpt,
      __sign,
      __buf,
      __len,
    );
  }

  late final _ecvt_r_ptr = _lookup<ffi.NativeFunction<_c_ecvt_r>>('ecvt_r');
  late final _dart_ecvt_r _ecvt_r = _ecvt_r_ptr.asFunction<_dart_ecvt_r>();

  int fcvt_r(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int32> __decpt,
    ffi.Pointer<ffi.Int32> __sign,
    ffi.Pointer<ffi.Int8> __buf,
    int __len,
  ) {
    return _fcvt_r(
      __value,
      __ndigit,
      __decpt,
      __sign,
      __buf,
      __len,
    );
  }

  late final _fcvt_r_ptr = _lookup<ffi.NativeFunction<_c_fcvt_r>>('fcvt_r');
  late final _dart_fcvt_r _fcvt_r = _fcvt_r_ptr.asFunction<_dart_fcvt_r>();

  int mblen(
    ffi.Pointer<ffi.Int8> __s,
    int __n,
  ) {
    return _mblen(
      __s,
      __n,
    );
  }

  late final _mblen_ptr = _lookup<ffi.NativeFunction<_c_mblen>>('mblen');
  late final _dart_mblen _mblen = _mblen_ptr.asFunction<_dart_mblen>();

  int mbtowc(
    ffi.Pointer<ffi.Int32> __pwc,
    ffi.Pointer<ffi.Int8> __s,
    int __n,
  ) {
    return _mbtowc(
      __pwc,
      __s,
      __n,
    );
  }

  late final _mbtowc_ptr = _lookup<ffi.NativeFunction<_c_mbtowc>>('mbtowc');
  late final _dart_mbtowc _mbtowc = _mbtowc_ptr.asFunction<_dart_mbtowc>();

  int wctomb(
    ffi.Pointer<ffi.Int8> __s,
    int __wchar,
  ) {
    return _wctomb(
      __s,
      __wchar,
    );
  }

  late final _wctomb_ptr = _lookup<ffi.NativeFunction<_c_wctomb>>('wctomb');
  late final _dart_wctomb _wctomb = _wctomb_ptr.asFunction<_dart_wctomb>();

  int mbstowcs(
    ffi.Pointer<ffi.Int32> __pwcs,
    ffi.Pointer<ffi.Int8> __s,
    int __n,
  ) {
    return _mbstowcs(
      __pwcs,
      __s,
      __n,
    );
  }

  late final _mbstowcs_ptr =
      _lookup<ffi.NativeFunction<_c_mbstowcs>>('mbstowcs');
  late final _dart_mbstowcs _mbstowcs =
      _mbstowcs_ptr.asFunction<_dart_mbstowcs>();

  int wcstombs(
    ffi.Pointer<ffi.Int8> __s,
    ffi.Pointer<ffi.Int32> __pwcs,
    int __n,
  ) {
    return _wcstombs(
      __s,
      __pwcs,
      __n,
    );
  }

  late final _wcstombs_ptr =
      _lookup<ffi.NativeFunction<_c_wcstombs>>('wcstombs');
  late final _dart_wcstombs _wcstombs =
      _wcstombs_ptr.asFunction<_dart_wcstombs>();

  int rpmatch(
    ffi.Pointer<ffi.Int8> __response,
  ) {
    return _rpmatch(
      __response,
    );
  }

  late final _rpmatch_ptr = _lookup<ffi.NativeFunction<_c_rpmatch>>('rpmatch');
  late final _dart_rpmatch _rpmatch = _rpmatch_ptr.asFunction<_dart_rpmatch>();

  int getsubopt(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __optionp,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __tokens,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __valuep,
  ) {
    return _getsubopt(
      __optionp,
      __tokens,
      __valuep,
    );
  }

  late final _getsubopt_ptr =
      _lookup<ffi.NativeFunction<_c_getsubopt>>('getsubopt');
  late final _dart_getsubopt _getsubopt =
      _getsubopt_ptr.asFunction<_dart_getsubopt>();

  int getloadavg(
    ffi.Pointer<ffi.Double> __loadavg,
    int __nelem,
  ) {
    return _getloadavg(
      __loadavg,
      __nelem,
    );
  }

  late final _getloadavg_ptr =
      _lookup<ffi.NativeFunction<_c_getloadavg>>('getloadavg');
  late final _dart_getloadavg _getloadavg =
      _getloadavg_ptr.asFunction<_dart_getloadavg>();

  void wrenInitConfiguration(
    ffi.Pointer<WrenConfiguration> configuration,
  ) {
    return _wrenInitConfiguration(
      configuration,
    );
  }

  late final _wrenInitConfiguration_ptr =
      _lookup<ffi.NativeFunction<_c_wrenInitConfiguration>>(
          'wrenInitConfiguration');
  late final _dart_wrenInitConfiguration _wrenInitConfiguration =
      _wrenInitConfiguration_ptr.asFunction<_dart_wrenInitConfiguration>();

  ffi.Pointer<WrenVM> wrenNewVM(
    ffi.Pointer<WrenConfiguration> configuration,
  ) {
    return _wrenNewVM(
      configuration,
    );
  }

  late final _wrenNewVM_ptr =
      _lookup<ffi.NativeFunction<_c_wrenNewVM>>('wrenNewVM');
  late final _dart_wrenNewVM _wrenNewVM =
      _wrenNewVM_ptr.asFunction<_dart_wrenNewVM>();

  void wrenFreeVM(
    ffi.Pointer<WrenVM> vm,
  ) {
    return _wrenFreeVM(
      vm,
    );
  }

  late final _wrenFreeVM_ptr =
      _lookup<ffi.NativeFunction<_c_wrenFreeVM>>('wrenFreeVM');
  late final _dart_wrenFreeVM _wrenFreeVM =
      _wrenFreeVM_ptr.asFunction<_dart_wrenFreeVM>();

  void wrenCollectGarbage(
    ffi.Pointer<WrenVM> vm,
  ) {
    return _wrenCollectGarbage(
      vm,
    );
  }

  late final _wrenCollectGarbage_ptr =
      _lookup<ffi.NativeFunction<_c_wrenCollectGarbage>>('wrenCollectGarbage');
  late final _dart_wrenCollectGarbage _wrenCollectGarbage =
      _wrenCollectGarbage_ptr.asFunction<_dart_wrenCollectGarbage>();

  int wrenInterpret(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Int8> module,
    ffi.Pointer<ffi.Int8> source,
  ) {
    return _wrenInterpret(
      vm,
      module,
      source,
    );
  }

  late final _wrenInterpret_ptr =
      _lookup<ffi.NativeFunction<_c_wrenInterpret>>('wrenInterpret');
  late final _dart_wrenInterpret _wrenInterpret =
      _wrenInterpret_ptr.asFunction<_dart_wrenInterpret>();

  ffi.Pointer<WrenHandle> wrenMakeCallHandle(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Int8> signature,
  ) {
    return _wrenMakeCallHandle(
      vm,
      signature,
    );
  }

  late final _wrenMakeCallHandle_ptr =
      _lookup<ffi.NativeFunction<_c_wrenMakeCallHandle>>('wrenMakeCallHandle');
  late final _dart_wrenMakeCallHandle _wrenMakeCallHandle =
      _wrenMakeCallHandle_ptr.asFunction<_dart_wrenMakeCallHandle>();

  int wrenCall(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<WrenHandle> method,
  ) {
    return _wrenCall(
      vm,
      method,
    );
  }

  late final _wrenCall_ptr =
      _lookup<ffi.NativeFunction<_c_wrenCall>>('wrenCall');
  late final _dart_wrenCall _wrenCall =
      _wrenCall_ptr.asFunction<_dart_wrenCall>();

  void wrenReleaseHandle(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<WrenHandle> handle,
  ) {
    return _wrenReleaseHandle(
      vm,
      handle,
    );
  }

  late final _wrenReleaseHandle_ptr =
      _lookup<ffi.NativeFunction<_c_wrenReleaseHandle>>('wrenReleaseHandle');
  late final _dart_wrenReleaseHandle _wrenReleaseHandle =
      _wrenReleaseHandle_ptr.asFunction<_dart_wrenReleaseHandle>();

  int wrenGetSlotCount(
    ffi.Pointer<WrenVM> vm,
  ) {
    return _wrenGetSlotCount(
      vm,
    );
  }

  late final _wrenGetSlotCount_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotCount>>('wrenGetSlotCount');
  late final _dart_wrenGetSlotCount _wrenGetSlotCount =
      _wrenGetSlotCount_ptr.asFunction<_dart_wrenGetSlotCount>();

  void wrenEnsureSlots(
    ffi.Pointer<WrenVM> vm,
    int numSlots,
  ) {
    return _wrenEnsureSlots(
      vm,
      numSlots,
    );
  }

  late final _wrenEnsureSlots_ptr =
      _lookup<ffi.NativeFunction<_c_wrenEnsureSlots>>('wrenEnsureSlots');
  late final _dart_wrenEnsureSlots _wrenEnsureSlots =
      _wrenEnsureSlots_ptr.asFunction<_dart_wrenEnsureSlots>();

  int wrenGetSlotType(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotType(
      vm,
      slot,
    );
  }

  late final _wrenGetSlotType_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotType>>('wrenGetSlotType');
  late final _dart_wrenGetSlotType _wrenGetSlotType =
      _wrenGetSlotType_ptr.asFunction<_dart_wrenGetSlotType>();

  bool wrenGetSlotBool(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotBool(
          vm,
          slot,
        ) !=
        0;
  }

  late final _wrenGetSlotBool_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotBool>>('wrenGetSlotBool');
  late final _dart_wrenGetSlotBool _wrenGetSlotBool =
      _wrenGetSlotBool_ptr.asFunction<_dart_wrenGetSlotBool>();

  ffi.Pointer<ffi.Int8> wrenGetSlotBytes(
    ffi.Pointer<WrenVM> vm,
    int slot,
    ffi.Pointer<ffi.Int32> length,
  ) {
    return _wrenGetSlotBytes(
      vm,
      slot,
      length,
    );
  }

  late final _wrenGetSlotBytes_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotBytes>>('wrenGetSlotBytes');
  late final _dart_wrenGetSlotBytes _wrenGetSlotBytes =
      _wrenGetSlotBytes_ptr.asFunction<_dart_wrenGetSlotBytes>();

  double wrenGetSlotDouble(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotDouble(
      vm,
      slot,
    );
  }

  late final _wrenGetSlotDouble_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotDouble>>('wrenGetSlotDouble');
  late final _dart_wrenGetSlotDouble _wrenGetSlotDouble =
      _wrenGetSlotDouble_ptr.asFunction<_dart_wrenGetSlotDouble>();

  ffi.Pointer<ffi.Void> wrenGetSlotForeign(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotForeign(
      vm,
      slot,
    );
  }

  late final _wrenGetSlotForeign_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotForeign>>('wrenGetSlotForeign');
  late final _dart_wrenGetSlotForeign _wrenGetSlotForeign =
      _wrenGetSlotForeign_ptr.asFunction<_dart_wrenGetSlotForeign>();

  ffi.Pointer<ffi.Int8> wrenGetSlotString(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotString(
      vm,
      slot,
    );
  }

  late final _wrenGetSlotString_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotString>>('wrenGetSlotString');
  late final _dart_wrenGetSlotString _wrenGetSlotString =
      _wrenGetSlotString_ptr.asFunction<_dart_wrenGetSlotString>();

  ffi.Pointer<WrenHandle> wrenGetSlotHandle(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetSlotHandle(
      vm,
      slot,
    );
  }

  late final _wrenGetSlotHandle_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetSlotHandle>>('wrenGetSlotHandle');
  late final _dart_wrenGetSlotHandle _wrenGetSlotHandle =
      _wrenGetSlotHandle_ptr.asFunction<_dart_wrenGetSlotHandle>();

  void wrenSetSlotBool(
    ffi.Pointer<WrenVM> vm,
    int slot,
    bool value,
  ) {
    return _wrenSetSlotBool(
      vm,
      slot,
      value ? 1 : 0,
    );
  }

  late final _wrenSetSlotBool_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotBool>>('wrenSetSlotBool');
  late final _dart_wrenSetSlotBool _wrenSetSlotBool =
      _wrenSetSlotBool_ptr.asFunction<_dart_wrenSetSlotBool>();

  void wrenSetSlotBytes(
    ffi.Pointer<WrenVM> vm,
    int slot,
    ffi.Pointer<ffi.Int8> bytes,
    int length,
  ) {
    return _wrenSetSlotBytes(
      vm,
      slot,
      bytes,
      length,
    );
  }

  late final _wrenSetSlotBytes_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotBytes>>('wrenSetSlotBytes');
  late final _dart_wrenSetSlotBytes _wrenSetSlotBytes =
      _wrenSetSlotBytes_ptr.asFunction<_dart_wrenSetSlotBytes>();

  void wrenSetSlotDouble(
    ffi.Pointer<WrenVM> vm,
    int slot,
    double value,
  ) {
    return _wrenSetSlotDouble(
      vm,
      slot,
      value,
    );
  }

  late final _wrenSetSlotDouble_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotDouble>>('wrenSetSlotDouble');
  late final _dart_wrenSetSlotDouble _wrenSetSlotDouble =
      _wrenSetSlotDouble_ptr.asFunction<_dart_wrenSetSlotDouble>();

  ffi.Pointer<ffi.Void> wrenSetSlotNewForeign(
    ffi.Pointer<WrenVM> vm,
    int slot,
    int classSlot,
    int size,
  ) {
    return _wrenSetSlotNewForeign(
      vm,
      slot,
      classSlot,
      size,
    );
  }

  late final _wrenSetSlotNewForeign_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotNewForeign>>(
          'wrenSetSlotNewForeign');
  late final _dart_wrenSetSlotNewForeign _wrenSetSlotNewForeign =
      _wrenSetSlotNewForeign_ptr.asFunction<_dart_wrenSetSlotNewForeign>();

  void wrenSetSlotNewList(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenSetSlotNewList(
      vm,
      slot,
    );
  }

  late final _wrenSetSlotNewList_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotNewList>>('wrenSetSlotNewList');
  late final _dart_wrenSetSlotNewList _wrenSetSlotNewList =
      _wrenSetSlotNewList_ptr.asFunction<_dart_wrenSetSlotNewList>();

  void wrenSetSlotNewMap(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenSetSlotNewMap(
      vm,
      slot,
    );
  }

  late final _wrenSetSlotNewMap_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotNewMap>>('wrenSetSlotNewMap');
  late final _dart_wrenSetSlotNewMap _wrenSetSlotNewMap =
      _wrenSetSlotNewMap_ptr.asFunction<_dart_wrenSetSlotNewMap>();

  void wrenSetSlotNull(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenSetSlotNull(
      vm,
      slot,
    );
  }

  late final _wrenSetSlotNull_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotNull>>('wrenSetSlotNull');
  late final _dart_wrenSetSlotNull _wrenSetSlotNull =
      _wrenSetSlotNull_ptr.asFunction<_dart_wrenSetSlotNull>();

  void wrenSetSlotString(
    ffi.Pointer<WrenVM> vm,
    int slot,
    ffi.Pointer<ffi.Int8> text,
  ) {
    return _wrenSetSlotString(
      vm,
      slot,
      text,
    );
  }

  late final _wrenSetSlotString_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotString>>('wrenSetSlotString');
  late final _dart_wrenSetSlotString _wrenSetSlotString =
      _wrenSetSlotString_ptr.asFunction<_dart_wrenSetSlotString>();

  void wrenSetSlotHandle(
    ffi.Pointer<WrenVM> vm,
    int slot,
    ffi.Pointer<WrenHandle> handle,
  ) {
    return _wrenSetSlotHandle(
      vm,
      slot,
      handle,
    );
  }

  late final _wrenSetSlotHandle_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetSlotHandle>>('wrenSetSlotHandle');
  late final _dart_wrenSetSlotHandle _wrenSetSlotHandle =
      _wrenSetSlotHandle_ptr.asFunction<_dart_wrenSetSlotHandle>();

  int wrenGetListCount(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetListCount(
      vm,
      slot,
    );
  }

  late final _wrenGetListCount_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetListCount>>('wrenGetListCount');
  late final _dart_wrenGetListCount _wrenGetListCount =
      _wrenGetListCount_ptr.asFunction<_dart_wrenGetListCount>();

  void wrenGetListElement(
    ffi.Pointer<WrenVM> vm,
    int listSlot,
    int index,
    int elementSlot,
  ) {
    return _wrenGetListElement(
      vm,
      listSlot,
      index,
      elementSlot,
    );
  }

  late final _wrenGetListElement_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetListElement>>('wrenGetListElement');
  late final _dart_wrenGetListElement _wrenGetListElement =
      _wrenGetListElement_ptr.asFunction<_dart_wrenGetListElement>();

  void wrenSetListElement(
    ffi.Pointer<WrenVM> vm,
    int listSlot,
    int index,
    int elementSlot,
  ) {
    return _wrenSetListElement(
      vm,
      listSlot,
      index,
      elementSlot,
    );
  }

  late final _wrenSetListElement_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetListElement>>('wrenSetListElement');
  late final _dart_wrenSetListElement _wrenSetListElement =
      _wrenSetListElement_ptr.asFunction<_dart_wrenSetListElement>();

  void wrenInsertInList(
    ffi.Pointer<WrenVM> vm,
    int listSlot,
    int index,
    int elementSlot,
  ) {
    return _wrenInsertInList(
      vm,
      listSlot,
      index,
      elementSlot,
    );
  }

  late final _wrenInsertInList_ptr =
      _lookup<ffi.NativeFunction<_c_wrenInsertInList>>('wrenInsertInList');
  late final _dart_wrenInsertInList _wrenInsertInList =
      _wrenInsertInList_ptr.asFunction<_dart_wrenInsertInList>();

  int wrenGetMapCount(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenGetMapCount(
      vm,
      slot,
    );
  }

  late final _wrenGetMapCount_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetMapCount>>('wrenGetMapCount');
  late final _dart_wrenGetMapCount _wrenGetMapCount =
      _wrenGetMapCount_ptr.asFunction<_dart_wrenGetMapCount>();

  bool wrenGetMapContainsKey(
    ffi.Pointer<WrenVM> vm,
    int mapSlot,
    int keySlot,
  ) {
    return _wrenGetMapContainsKey(
          vm,
          mapSlot,
          keySlot,
        ) !=
        0;
  }

  late final _wrenGetMapContainsKey_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetMapContainsKey>>(
          'wrenGetMapContainsKey');
  late final _dart_wrenGetMapContainsKey _wrenGetMapContainsKey =
      _wrenGetMapContainsKey_ptr.asFunction<_dart_wrenGetMapContainsKey>();

  void wrenGetMapValue(
    ffi.Pointer<WrenVM> vm,
    int mapSlot,
    int keySlot,
    int valueSlot,
  ) {
    return _wrenGetMapValue(
      vm,
      mapSlot,
      keySlot,
      valueSlot,
    );
  }

  late final _wrenGetMapValue_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetMapValue>>('wrenGetMapValue');
  late final _dart_wrenGetMapValue _wrenGetMapValue =
      _wrenGetMapValue_ptr.asFunction<_dart_wrenGetMapValue>();

  void wrenSetMapValue(
    ffi.Pointer<WrenVM> vm,
    int mapSlot,
    int keySlot,
    int valueSlot,
  ) {
    return _wrenSetMapValue(
      vm,
      mapSlot,
      keySlot,
      valueSlot,
    );
  }

  late final _wrenSetMapValue_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetMapValue>>('wrenSetMapValue');
  late final _dart_wrenSetMapValue _wrenSetMapValue =
      _wrenSetMapValue_ptr.asFunction<_dart_wrenSetMapValue>();

  void wrenRemoveMapValue(
    ffi.Pointer<WrenVM> vm,
    int mapSlot,
    int keySlot,
    int removedValueSlot,
  ) {
    return _wrenRemoveMapValue(
      vm,
      mapSlot,
      keySlot,
      removedValueSlot,
    );
  }

  late final _wrenRemoveMapValue_ptr =
      _lookup<ffi.NativeFunction<_c_wrenRemoveMapValue>>('wrenRemoveMapValue');
  late final _dart_wrenRemoveMapValue _wrenRemoveMapValue =
      _wrenRemoveMapValue_ptr.asFunction<_dart_wrenRemoveMapValue>();

  void wrenGetVariable(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Int8> module,
    ffi.Pointer<ffi.Int8> name,
    int slot,
  ) {
    return _wrenGetVariable(
      vm,
      module,
      name,
      slot,
    );
  }

  late final _wrenGetVariable_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetVariable>>('wrenGetVariable');
  late final _dart_wrenGetVariable _wrenGetVariable =
      _wrenGetVariable_ptr.asFunction<_dart_wrenGetVariable>();

  bool wrenHasVariable(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Int8> module,
    ffi.Pointer<ffi.Int8> name,
  ) {
    return _wrenHasVariable(
          vm,
          module,
          name,
        ) !=
        0;
  }

  late final _wrenHasVariable_ptr =
      _lookup<ffi.NativeFunction<_c_wrenHasVariable>>('wrenHasVariable');
  late final _dart_wrenHasVariable _wrenHasVariable =
      _wrenHasVariable_ptr.asFunction<_dart_wrenHasVariable>();

  bool wrenHasModule(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Int8> module,
  ) {
    return _wrenHasModule(
          vm,
          module,
        ) !=
        0;
  }

  late final _wrenHasModule_ptr =
      _lookup<ffi.NativeFunction<_c_wrenHasModule>>('wrenHasModule');
  late final _dart_wrenHasModule _wrenHasModule =
      _wrenHasModule_ptr.asFunction<_dart_wrenHasModule>();

  void wrenAbortFiber(
    ffi.Pointer<WrenVM> vm,
    int slot,
  ) {
    return _wrenAbortFiber(
      vm,
      slot,
    );
  }

  late final _wrenAbortFiber_ptr =
      _lookup<ffi.NativeFunction<_c_wrenAbortFiber>>('wrenAbortFiber');
  late final _dart_wrenAbortFiber _wrenAbortFiber =
      _wrenAbortFiber_ptr.asFunction<_dart_wrenAbortFiber>();

  ffi.Pointer<ffi.Void> wrenGetUserData(
    ffi.Pointer<WrenVM> vm,
  ) {
    return _wrenGetUserData(
      vm,
    );
  }

  late final _wrenGetUserData_ptr =
      _lookup<ffi.NativeFunction<_c_wrenGetUserData>>('wrenGetUserData');
  late final _dart_wrenGetUserData _wrenGetUserData =
      _wrenGetUserData_ptr.asFunction<_dart_wrenGetUserData>();

  void wrenSetUserData(
    ffi.Pointer<WrenVM> vm,
    ffi.Pointer<ffi.Void> userData,
  ) {
    return _wrenSetUserData(
      vm,
      userData,
    );
  }

  late final _wrenSetUserData_ptr =
      _lookup<ffi.NativeFunction<_c_wrenSetUserData>>('wrenSetUserData');
  late final _dart_wrenSetUserData _wrenSetUserData =
      _wrenSetUserData_ptr.asFunction<_dart_wrenSetUserData>();
}

abstract class idtype_t {
  static const int P_ALL = 0;
  static const int P_PID = 1;
  static const int P_PGID = 2;
}

class div_t extends ffi.Struct {
  @ffi.Int32()
  external int quot;

  @ffi.Int32()
  external int rem;
}

class ldiv_t extends ffi.Struct {
  @ffi.Int64()
  external int quot;

  @ffi.Int64()
  external int rem;
}

class lldiv_t extends ffi.Struct {
  @ffi.Int64()
  external int quot;

  @ffi.Int64()
  external int rem;
}

class __fsid_t extends ffi.Opaque {}

class __sigset_t extends ffi.Opaque {}

class timeval extends ffi.Struct {
  @ffi.Int64()
  external int tv_sec;

  @ffi.Int64()
  external int tv_usec;
}

class timespec extends ffi.Struct {
  @ffi.Int64()
  external int tv_sec;

  @ffi.Int64()
  external int tv_nsec;
}

class fd_set extends ffi.Opaque {}

class __pthread_list_t extends ffi.Struct {
  external ffi.Pointer<__pthread_list_t> __prev;

  external ffi.Pointer<__pthread_list_t> __next;
}

class __pthread_slist_t extends ffi.Struct {
  external ffi.Pointer<__pthread_slist_t> __next;
}

class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int32()
  external int __lock;

  @ffi.Uint32()
  external int __count;

  @ffi.Int32()
  external int __owner;

  @ffi.Uint32()
  external int __nusers;

  @ffi.Int32()
  external int __kind;

  @ffi.Int16()
  external int __spins;

  @ffi.Int16()
  external int __elision;

  external __pthread_list_t __list;
}

class __pthread_rwlock_arch_t extends ffi.Opaque {}

class __pthread_cond_s extends ffi.Opaque {}

class __once_flag extends ffi.Struct {
  @ffi.Int32()
  external int __data;
}

class random_data extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> fptr;

  external ffi.Pointer<ffi.Int32> rptr;

  external ffi.Pointer<ffi.Int32> state;

  @ffi.Int32()
  external int rand_type;

  @ffi.Int32()
  external int rand_deg;

  @ffi.Int32()
  external int rand_sep;

  external ffi.Pointer<ffi.Int32> end_ptr;
}

class drand48_data extends ffi.Opaque {}

class WrenVM extends ffi.Opaque {}

class WrenHandle extends ffi.Opaque {}

class WrenLoadModuleResult extends ffi.Struct {
  external ffi.Pointer<ffi.Int8> source;

  external ffi.Pointer<ffi.NativeFunction<WrenLoadModuleCompleteFn>> onComplete;

  external ffi.Pointer<ffi.Void> userData;
}

abstract class WrenErrorType {
  static const int WREN_ERROR_COMPILE = 0;
  static const int WREN_ERROR_RUNTIME = 1;
  static const int WREN_ERROR_STACK_TRACE = 2;
}

class WrenForeignClassMethods extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<WrenForeignMethodFn>> allocate;

  external ffi.Pointer<ffi.NativeFunction<WrenFinalizerFn>> finalize;
}

class WrenConfiguration extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<WrenReallocateFn>> reallocateFn;

  external ffi.Pointer<ffi.NativeFunction<WrenResolveModuleFn>> resolveModuleFn;

  external ffi.Pointer<ffi.NativeFunction<WrenLoadModuleFn>> loadModuleFn;

  external ffi.Pointer<ffi.NativeFunction<WrenBindForeignMethodFn>>
      bindForeignMethodFn;

  external ffi.Pointer<ffi.NativeFunction<WrenBindForeignClassFn>>
      bindForeignClassFn;

  external ffi.Pointer<ffi.NativeFunction<WrenWriteFn>> writeFn;

  external ffi.Pointer<ffi.NativeFunction<WrenErrorFn>> errorFn;

  @ffi.Uint64()
  external int initialHeapSize;

  @ffi.Uint64()
  external int minHeapSize;

  @ffi.Int32()
  external int heapGrowthPercent;

  external ffi.Pointer<ffi.Void> userData;
}

abstract class WrenInterpretResult {
  static const int WREN_RESULT_SUCCESS = 0;
  static const int WREN_RESULT_COMPILE_ERROR = 1;
  static const int WREN_RESULT_RUNTIME_ERROR = 2;
}

abstract class WrenType {
  static const int WREN_TYPE_BOOL = 0;
  static const int WREN_TYPE_NUM = 1;
  static const int WREN_TYPE_FOREIGN = 2;
  static const int WREN_TYPE_LIST = 3;
  static const int WREN_TYPE_MAP = 4;
  static const int WREN_TYPE_NULL = 5;
  static const int WREN_TYPE_STRING = 6;
  static const int WREN_TYPE_UNKNOWN = 7;
}

const int __GNUC_VA_LIST = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 27;

const int _SYS_CDEFS_H = 1;

const int __glibc_c99_flexarr_available = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int NULL = 0;

const int _STDLIB_H = 1;

const int WNOHANG = 1;

const int WUNTRACED = 2;

const int WSTOPPED = 2;

const int WEXITED = 4;

const int WCONTINUED = 8;

const int WNOWAIT = 16777216;

const int __WNOTHREAD = 536870912;

const int __WALL = 1073741824;

const int __WCLONE = 2147483648;

const int __ENUM_IDTYPE_T = 1;

const int __W_CONTINUED = 65535;

const int __WCOREFLAG = 128;

const int __HAVE_FLOAT128 = 0;

const int __HAVE_DISTINCT_FLOAT128 = 0;

const int __HAVE_FLOAT64X = 1;

const int __HAVE_FLOAT64X_LONG_DOUBLE = 1;

const int __HAVE_FLOAT16 = 0;

const int __HAVE_FLOAT32 = 1;

const int __HAVE_FLOAT64 = 1;

const int __HAVE_FLOAT32X = 1;

const int __HAVE_FLOAT128X = 0;

const int __HAVE_DISTINCT_FLOAT16 = 0;

const int __HAVE_DISTINCT_FLOAT32 = 0;

const int __HAVE_DISTINCT_FLOAT64 = 0;

const int __HAVE_DISTINCT_FLOAT32X = 0;

const int __HAVE_DISTINCT_FLOAT64X = 0;

const int __HAVE_DISTINCT_FLOAT128X = 0;

const int __HAVE_FLOATN_NOT_TYPEDEF = 0;

const int __ldiv_t_defined = 1;

const int __lldiv_t_defined = 1;

const int RAND_MAX = 2147483647;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int _SYS_TYPES_H = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __FD_SETSIZE = 1024;

const int __clock_t_defined = 1;

const int __clockid_t_defined = 1;

const int __time_t_defined = 1;

const int __timer_t_defined = 1;

const int _BITS_STDINT_INTN_H = 1;

const int __BIT_TYPES_DEFINED__ = 1;

const int _ENDIAN_H = 1;

const int __LITTLE_ENDIAN = 1234;

const int __BIG_ENDIAN = 4321;

const int __PDP_ENDIAN = 3412;

const int __BYTE_ORDER = 1234;

const int __FLOAT_WORD_ORDER = 1234;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int _BITS_BYTESWAP_H = 1;

const int _BITS_UINTN_IDENTITY_H = 1;

const int _SYS_SELECT_H = 1;

const int __sigset_t_defined = 1;

const int _SIGSET_NWORDS = 16;

const int __timeval_defined = 1;

const int _STRUCT_TIMESPEC = 1;

const int __NFDBITS = 64;

const int FD_SETSIZE = 1024;

const int NFDBITS = 64;

const int _BITS_PTHREADTYPES_COMMON_H = 1;

const int _THREAD_SHARED_TYPES_H = 1;

const int _BITS_PTHREADTYPES_ARCH_H = 1;

const int __SIZEOF_PTHREAD_MUTEX_T = 40;

const int __SIZEOF_PTHREAD_ATTR_T = 56;

const int __SIZEOF_PTHREAD_RWLOCK_T = 56;

const int __SIZEOF_PTHREAD_BARRIER_T = 32;

const int __SIZEOF_PTHREAD_MUTEXATTR_T = 4;

const int __SIZEOF_PTHREAD_COND_T = 48;

const int __SIZEOF_PTHREAD_CONDATTR_T = 4;

const int __SIZEOF_PTHREAD_RWLOCKATTR_T = 8;

const int __SIZEOF_PTHREAD_BARRIERATTR_T = 4;

const int __PTHREAD_MUTEX_HAVE_PREV = 1;

const int __PTHREAD_RWLOCK_ELISION_EXTRA = 0;

const int __have_pthread_attr_t = 1;

const int _ALLOCA_H = 1;

const int true_1 = 1;

const int false_1 = 0;

const int __bool_true_false_are_defined = 1;

const int WREN_VERSION_MAJOR = 0;

const int WREN_VERSION_MINOR = 4;

const int WREN_VERSION_PATCH = 0;

const String WREN_VERSION_STRING = '0.4.0';

const int WREN_VERSION_NUMBER = 4000;

typedef _c___ctype_get_mb_cur_max = ffi.Uint64 Function();

typedef _dart___ctype_get_mb_cur_max = int Function();

typedef _c_atof = ffi.Double Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _dart_atof = double Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _c_atoi = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _dart_atoi = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _c_atol = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _dart_atol = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _c_atoll = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _dart_atoll = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
);

typedef _c_strtod = ffi.Double Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
);

typedef _dart_strtod = double Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
);

typedef _c_strtof = ffi.Float Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
);

typedef _dart_strtof = double Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
);

typedef _c_strtol = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtol = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoul = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoul = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoq = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoq = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtouq = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtouq = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoll = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoll = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoull = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoull = int Function(
  ffi.Pointer<ffi.Int8> __nptr,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_l64a = ffi.Pointer<ffi.Int8> Function(
  ffi.Int64 __n,
);

typedef _dart_l64a = ffi.Pointer<ffi.Int8> Function(
  int __n,
);

typedef _c_a64l = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __s,
);

typedef _dart_a64l = int Function(
  ffi.Pointer<ffi.Int8> __s,
);

typedef _c_select = ffi.Int32 Function(
  ffi.Int32 __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timeval> __timeout,
);

typedef _dart_select = int Function(
  int __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timeval> __timeout,
);

typedef _c_pselect = ffi.Int32 Function(
  ffi.Int32 __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timespec> __timeout,
  ffi.Pointer<__sigset_t> __sigmask,
);

typedef _dart_pselect = int Function(
  int __nfds,
  ffi.Pointer<fd_set> __readfds,
  ffi.Pointer<fd_set> __writefds,
  ffi.Pointer<fd_set> __exceptfds,
  ffi.Pointer<timespec> __timeout,
  ffi.Pointer<__sigset_t> __sigmask,
);

typedef _c_random = ffi.Int64 Function();

typedef _dart_random = int Function();

typedef _c_srandom = ffi.Void Function(
  ffi.Uint32 __seed,
);

typedef _dart_srandom = void Function(
  int __seed,
);

typedef _c_initstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Uint32 __seed,
  ffi.Pointer<ffi.Int8> __statebuf,
  ffi.Uint64 __statelen,
);

typedef _dart_initstate = ffi.Pointer<ffi.Int8> Function(
  int __seed,
  ffi.Pointer<ffi.Int8> __statebuf,
  int __statelen,
);

typedef _c_setstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __statebuf,
);

typedef _dart_setstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __statebuf,
);

typedef _c_random_r = ffi.Int32 Function(
  ffi.Pointer<random_data> __buf,
  ffi.Pointer<ffi.Int32> __result,
);

typedef _dart_random_r = int Function(
  ffi.Pointer<random_data> __buf,
  ffi.Pointer<ffi.Int32> __result,
);

typedef _c_srandom_r = ffi.Int32 Function(
  ffi.Uint32 __seed,
  ffi.Pointer<random_data> __buf,
);

typedef _dart_srandom_r = int Function(
  int __seed,
  ffi.Pointer<random_data> __buf,
);

typedef _c_initstate_r = ffi.Int32 Function(
  ffi.Uint32 __seed,
  ffi.Pointer<ffi.Int8> __statebuf,
  ffi.Uint64 __statelen,
  ffi.Pointer<random_data> __buf,
);

typedef _dart_initstate_r = int Function(
  int __seed,
  ffi.Pointer<ffi.Int8> __statebuf,
  int __statelen,
  ffi.Pointer<random_data> __buf,
);

typedef _c_setstate_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __statebuf,
  ffi.Pointer<random_data> __buf,
);

typedef _dart_setstate_r = int Function(
  ffi.Pointer<ffi.Int8> __statebuf,
  ffi.Pointer<random_data> __buf,
);

typedef _c_rand = ffi.Int32 Function();

typedef _dart_rand = int Function();

typedef _c_srand = ffi.Void Function(
  ffi.Uint32 __seed,
);

typedef _dart_srand = void Function(
  int __seed,
);

typedef _c_rand_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint32> __seed,
);

typedef _dart_rand_r = int Function(
  ffi.Pointer<ffi.Uint32> __seed,
);

typedef _c_drand48 = ffi.Double Function();

typedef _dart_drand48 = double Function();

typedef _c_erand48 = ffi.Double Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _dart_erand48 = double Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _c_lrand48 = ffi.Int64 Function();

typedef _dart_lrand48 = int Function();

typedef _c_nrand48 = ffi.Int64 Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _dart_nrand48 = int Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _c_mrand48 = ffi.Int64 Function();

typedef _dart_mrand48 = int Function();

typedef _c_jrand48 = ffi.Int64 Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _dart_jrand48 = int Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
);

typedef _c_srand48 = ffi.Void Function(
  ffi.Int64 __seedval,
);

typedef _dart_srand48 = void Function(
  int __seedval,
);

typedef _c_seed48 = ffi.Pointer<ffi.Uint16> Function(
  ffi.Pointer<ffi.Uint16> __seed16v,
);

typedef _dart_seed48 = ffi.Pointer<ffi.Uint16> Function(
  ffi.Pointer<ffi.Uint16> __seed16v,
);

typedef _c_lcong48 = ffi.Void Function(
  ffi.Pointer<ffi.Uint16> __param,
);

typedef _dart_lcong48 = void Function(
  ffi.Pointer<ffi.Uint16> __param,
);

typedef _c_drand48_r = ffi.Int32 Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

typedef _dart_drand48_r = int Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

typedef _c_erand48_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

typedef _dart_erand48_r = int Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Double> __result,
);

typedef _c_lrand48_r = ffi.Int32 Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _dart_lrand48_r = int Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _c_nrand48_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _dart_nrand48_r = int Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _c_mrand48_r = ffi.Int32 Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _dart_mrand48_r = int Function(
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _c_jrand48_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _dart_jrand48_r = int Function(
  ffi.Pointer<ffi.Uint16> __xsubi,
  ffi.Pointer<drand48_data> __buffer,
  ffi.Pointer<ffi.Int64> __result,
);

typedef _c_srand48_r = ffi.Int32 Function(
  ffi.Int64 __seedval,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _dart_srand48_r = int Function(
  int __seedval,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _c_seed48_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint16> __seed16v,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _dart_seed48_r = int Function(
  ffi.Pointer<ffi.Uint16> __seed16v,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _c_lcong48_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint16> __param,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _dart_lcong48_r = int Function(
  ffi.Pointer<ffi.Uint16> __param,
  ffi.Pointer<drand48_data> __buffer,
);

typedef _c_malloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __size,
);

typedef _dart_malloc = ffi.Pointer<ffi.Void> Function(
  int __size,
);

typedef _c_calloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __nmemb,
  ffi.Uint64 __size,
);

typedef _dart_calloc = ffi.Pointer<ffi.Void> Function(
  int __nmemb,
  int __size,
);

typedef _c_realloc = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  ffi.Uint64 __size,
);

typedef _dart_realloc = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
);

typedef _c_reallocarray = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  ffi.Uint64 __nmemb,
  ffi.Uint64 __size,
);

typedef _dart_reallocarray = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  int __nmemb,
  int __size,
);

typedef _c_free = ffi.Void Function(
  ffi.Pointer<ffi.Void> __ptr,
);

typedef _dart_free = void Function(
  ffi.Pointer<ffi.Void> __ptr,
);

typedef _c_alloca = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __size,
);

typedef _dart_alloca = ffi.Pointer<ffi.Void> Function(
  int __size,
);

typedef _c_valloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __size,
);

typedef _dart_valloc = ffi.Pointer<ffi.Void> Function(
  int __size,
);

typedef _c_posix_memalign = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
  ffi.Uint64 __alignment,
  ffi.Uint64 __size,
);

typedef _dart_posix_memalign = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
  int __alignment,
  int __size,
);

typedef _c_aligned_alloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __alignment,
  ffi.Uint64 __size,
);

typedef _dart_aligned_alloc = ffi.Pointer<ffi.Void> Function(
  int __alignment,
  int __size,
);

typedef _c_abort = ffi.Void Function();

typedef _dart_abort = void Function();

typedef _typedefC_1 = ffi.Void Function();

typedef _c_atexit = ffi.Int32 Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> __func,
);

typedef _dart_atexit = int Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> __func,
);

typedef _typedefC_2 = ffi.Void Function();

typedef _c_at_quick_exit = ffi.Int32 Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_2>> __func,
);

typedef _dart_at_quick_exit = int Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_2>> __func,
);

typedef _typedefC_3 = ffi.Void Function(
  ffi.Int32,
  ffi.Pointer<ffi.Void>,
);

typedef _c_on_exit = ffi.Int32 Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_3>> __func,
  ffi.Pointer<ffi.Void> __arg,
);

typedef _dart_on_exit = int Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_3>> __func,
  ffi.Pointer<ffi.Void> __arg,
);

typedef _c_exit = ffi.Void Function(
  ffi.Int32 __status,
);

typedef _dart_exit = void Function(
  int __status,
);

typedef _c_quick_exit = ffi.Void Function(
  ffi.Int32 __status,
);

typedef _dart_quick_exit = void Function(
  int __status,
);

typedef _c__Exit = ffi.Void Function(
  ffi.Int32 __status,
);

typedef _dart__Exit = void Function(
  int __status,
);

typedef _c_getenv = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __name,
);

typedef _dart_getenv = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __name,
);

typedef _c_putenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __string,
);

typedef _dart_putenv = int Function(
  ffi.Pointer<ffi.Int8> __string,
);

typedef _c_setenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __value,
  ffi.Int32 __replace,
);

typedef _dart_setenv = int Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __value,
  int __replace,
);

typedef _c_unsetenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __name,
);

typedef _dart_unsetenv = int Function(
  ffi.Pointer<ffi.Int8> __name,
);

typedef _c_clearenv = ffi.Int32 Function();

typedef _dart_clearenv = int Function();

typedef _c_mktemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _dart_mktemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _c_mkstemp = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _dart_mkstemp = int Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _c_mkstemps = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __template,
  ffi.Int32 __suffixlen,
);

typedef _dart_mkstemps = int Function(
  ffi.Pointer<ffi.Int8> __template,
  int __suffixlen,
);

typedef _c_mkdtemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _dart_mkdtemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __template,
);

typedef _c_system = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __command,
);

typedef _dart_system = int Function(
  ffi.Pointer<ffi.Int8> __command,
);

typedef _c_realpath = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __resolved,
);

typedef _dart_realpath = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __resolved,
);

typedef __compar_fn_t = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_bsearch = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nmemb,
  ffi.Uint64 __size,
  ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
);

typedef _dart_bsearch = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  int __nmemb,
  int __size,
  ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
);

typedef _c_qsort = ffi.Void Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nmemb,
  ffi.Uint64 __size,
  ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
);

typedef _dart_qsort = void Function(
  ffi.Pointer<ffi.Void> __base,
  int __nmemb,
  int __size,
  ffi.Pointer<ffi.NativeFunction<__compar_fn_t>> __compar,
);

typedef _c_abs = ffi.Int32 Function(
  ffi.Int32 __x,
);

typedef _dart_abs = int Function(
  int __x,
);

typedef _c_labs = ffi.Int64 Function(
  ffi.Int64 __x,
);

typedef _dart_labs = int Function(
  int __x,
);

typedef _c_llabs = ffi.Int64 Function(
  ffi.Int64 __x,
);

typedef _dart_llabs = int Function(
  int __x,
);

typedef _c_div = div_t Function(
  ffi.Int32 __numer,
  ffi.Int32 __denom,
);

typedef _dart_div = div_t Function(
  int __numer,
  int __denom,
);

typedef _c_ldiv = ldiv_t Function(
  ffi.Int64 __numer,
  ffi.Int64 __denom,
);

typedef _dart_ldiv = ldiv_t Function(
  int __numer,
  int __denom,
);

typedef _c_lldiv = lldiv_t Function(
  ffi.Int64 __numer,
  ffi.Int64 __denom,
);

typedef _dart_lldiv = lldiv_t Function(
  int __numer,
  int __denom,
);

typedef _c_ecvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double __value,
  ffi.Int32 __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
);

typedef _dart_ecvt = ffi.Pointer<ffi.Int8> Function(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
);

typedef _c_fcvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double __value,
  ffi.Int32 __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
);

typedef _dart_fcvt = ffi.Pointer<ffi.Int8> Function(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
);

typedef _c_gcvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double __value,
  ffi.Int32 __ndigit,
  ffi.Pointer<ffi.Int8> __buf,
);

typedef _dart_gcvt = ffi.Pointer<ffi.Int8> Function(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int8> __buf,
);

typedef _c_ecvt_r = ffi.Int32 Function(
  ffi.Double __value,
  ffi.Int32 __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
  ffi.Pointer<ffi.Int8> __buf,
  ffi.Uint64 __len,
);

typedef _dart_ecvt_r = int Function(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
  ffi.Pointer<ffi.Int8> __buf,
  int __len,
);

typedef _c_fcvt_r = ffi.Int32 Function(
  ffi.Double __value,
  ffi.Int32 __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
  ffi.Pointer<ffi.Int8> __buf,
  ffi.Uint64 __len,
);

typedef _dart_fcvt_r = int Function(
  double __value,
  int __ndigit,
  ffi.Pointer<ffi.Int32> __decpt,
  ffi.Pointer<ffi.Int32> __sign,
  ffi.Pointer<ffi.Int8> __buf,
  int __len,
);

typedef _c_mblen = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __s,
  ffi.Uint64 __n,
);

typedef _dart_mblen = int Function(
  ffi.Pointer<ffi.Int8> __s,
  int __n,
);

typedef _c_mbtowc = ffi.Int32 Function(
  ffi.Pointer<ffi.Int32> __pwc,
  ffi.Pointer<ffi.Int8> __s,
  ffi.Uint64 __n,
);

typedef _dart_mbtowc = int Function(
  ffi.Pointer<ffi.Int32> __pwc,
  ffi.Pointer<ffi.Int8> __s,
  int __n,
);

typedef _c_wctomb = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __s,
  ffi.Int32 __wchar,
);

typedef _dart_wctomb = int Function(
  ffi.Pointer<ffi.Int8> __s,
  int __wchar,
);

typedef _c_mbstowcs = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int32> __pwcs,
  ffi.Pointer<ffi.Int8> __s,
  ffi.Uint64 __n,
);

typedef _dart_mbstowcs = int Function(
  ffi.Pointer<ffi.Int32> __pwcs,
  ffi.Pointer<ffi.Int8> __s,
  int __n,
);

typedef _c_wcstombs = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __s,
  ffi.Pointer<ffi.Int32> __pwcs,
  ffi.Uint64 __n,
);

typedef _dart_wcstombs = int Function(
  ffi.Pointer<ffi.Int8> __s,
  ffi.Pointer<ffi.Int32> __pwcs,
  int __n,
);

typedef _c_rpmatch = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __response,
);

typedef _dart_rpmatch = int Function(
  ffi.Pointer<ffi.Int8> __response,
);

typedef _c_getsubopt = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __optionp,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __tokens,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __valuep,
);

typedef _dart_getsubopt = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __optionp,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __tokens,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __valuep,
);

typedef _c_getloadavg = ffi.Int32 Function(
  ffi.Pointer<ffi.Double> __loadavg,
  ffi.Int32 __nelem,
);

typedef _dart_getloadavg = int Function(
  ffi.Pointer<ffi.Double> __loadavg,
  int __nelem,
);

typedef _c_wrenInitConfiguration = ffi.Void Function(
  ffi.Pointer<WrenConfiguration> configuration,
);

typedef _dart_wrenInitConfiguration = void Function(
  ffi.Pointer<WrenConfiguration> configuration,
);

typedef _c_wrenNewVM = ffi.Pointer<WrenVM> Function(
  ffi.Pointer<WrenConfiguration> configuration,
);

typedef _dart_wrenNewVM = ffi.Pointer<WrenVM> Function(
  ffi.Pointer<WrenConfiguration> configuration,
);

typedef _c_wrenFreeVM = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _dart_wrenFreeVM = void Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _c_wrenCollectGarbage = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _dart_wrenCollectGarbage = void Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _c_wrenInterpret = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> source,
);

typedef _dart_wrenInterpret = int Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> source,
);

typedef _c_wrenMakeCallHandle = ffi.Pointer<WrenHandle> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> signature,
);

typedef _dart_wrenMakeCallHandle = ffi.Pointer<WrenHandle> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> signature,
);

typedef _c_wrenCall = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<WrenHandle> method,
);

typedef _dart_wrenCall = int Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<WrenHandle> method,
);

typedef _c_wrenReleaseHandle = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<WrenHandle> handle,
);

typedef _dart_wrenReleaseHandle = void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<WrenHandle> handle,
);

typedef _c_wrenGetSlotCount = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _dart_wrenGetSlotCount = int Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _c_wrenEnsureSlots = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 numSlots,
);

typedef _dart_wrenEnsureSlots = void Function(
  ffi.Pointer<WrenVM> vm,
  int numSlots,
);

typedef _c_wrenGetSlotType = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotType = int Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetSlotBool = ffi.Uint8 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotBool = int Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetSlotBytes = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Pointer<ffi.Int32> length,
);

typedef _dart_wrenGetSlotBytes = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  ffi.Pointer<ffi.Int32> length,
);

typedef _c_wrenGetSlotDouble = ffi.Double Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotDouble = double Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetSlotForeign = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotForeign = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetSlotString = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotString = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetSlotHandle = ffi.Pointer<WrenHandle> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetSlotHandle = ffi.Pointer<WrenHandle> Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenSetSlotBool = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Uint8 value,
);

typedef _dart_wrenSetSlotBool = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  int value,
);

typedef _c_wrenSetSlotBytes = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Pointer<ffi.Int8> bytes,
  ffi.Uint64 length,
);

typedef _dart_wrenSetSlotBytes = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  ffi.Pointer<ffi.Int8> bytes,
  int length,
);

typedef _c_wrenSetSlotDouble = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Double value,
);

typedef _dart_wrenSetSlotDouble = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  double value,
);

typedef _c_wrenSetSlotNewForeign = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Int32 classSlot,
  ffi.Uint64 size,
);

typedef _dart_wrenSetSlotNewForeign = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  int classSlot,
  int size,
);

typedef _c_wrenSetSlotNewList = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenSetSlotNewList = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenSetSlotNewMap = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenSetSlotNewMap = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenSetSlotNull = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenSetSlotNull = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenSetSlotString = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Pointer<ffi.Int8> text,
);

typedef _dart_wrenSetSlotString = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  ffi.Pointer<ffi.Int8> text,
);

typedef _c_wrenSetSlotHandle = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
  ffi.Pointer<WrenHandle> handle,
);

typedef _dart_wrenSetSlotHandle = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
  ffi.Pointer<WrenHandle> handle,
);

typedef _c_wrenGetListCount = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetListCount = int Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetListElement = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 listSlot,
  ffi.Int32 index,
  ffi.Int32 elementSlot,
);

typedef _dart_wrenGetListElement = void Function(
  ffi.Pointer<WrenVM> vm,
  int listSlot,
  int index,
  int elementSlot,
);

typedef _c_wrenSetListElement = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 listSlot,
  ffi.Int32 index,
  ffi.Int32 elementSlot,
);

typedef _dart_wrenSetListElement = void Function(
  ffi.Pointer<WrenVM> vm,
  int listSlot,
  int index,
  int elementSlot,
);

typedef _c_wrenInsertInList = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 listSlot,
  ffi.Int32 index,
  ffi.Int32 elementSlot,
);

typedef _dart_wrenInsertInList = void Function(
  ffi.Pointer<WrenVM> vm,
  int listSlot,
  int index,
  int elementSlot,
);

typedef _c_wrenGetMapCount = ffi.Int32 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenGetMapCount = int Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetMapContainsKey = ffi.Uint8 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 mapSlot,
  ffi.Int32 keySlot,
);

typedef _dart_wrenGetMapContainsKey = int Function(
  ffi.Pointer<WrenVM> vm,
  int mapSlot,
  int keySlot,
);

typedef _c_wrenGetMapValue = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 mapSlot,
  ffi.Int32 keySlot,
  ffi.Int32 valueSlot,
);

typedef _dart_wrenGetMapValue = void Function(
  ffi.Pointer<WrenVM> vm,
  int mapSlot,
  int keySlot,
  int valueSlot,
);

typedef _c_wrenSetMapValue = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 mapSlot,
  ffi.Int32 keySlot,
  ffi.Int32 valueSlot,
);

typedef _dart_wrenSetMapValue = void Function(
  ffi.Pointer<WrenVM> vm,
  int mapSlot,
  int keySlot,
  int valueSlot,
);

typedef _c_wrenRemoveMapValue = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 mapSlot,
  ffi.Int32 keySlot,
  ffi.Int32 removedValueSlot,
);

typedef _dart_wrenRemoveMapValue = void Function(
  ffi.Pointer<WrenVM> vm,
  int mapSlot,
  int keySlot,
  int removedValueSlot,
);

typedef _c_wrenGetVariable = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> name,
  ffi.Int32 slot,
);

typedef _dart_wrenGetVariable = void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> name,
  int slot,
);

typedef _c_wrenHasVariable = ffi.Uint8 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> name,
);

typedef _dart_wrenHasVariable = int Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
  ffi.Pointer<ffi.Int8> name,
);

typedef _c_wrenHasModule = ffi.Uint8 Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
);

typedef _dart_wrenHasModule = int Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Int8> module,
);

typedef _c_wrenAbortFiber = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Int32 slot,
);

typedef _dart_wrenAbortFiber = void Function(
  ffi.Pointer<WrenVM> vm,
  int slot,
);

typedef _c_wrenGetUserData = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _dart_wrenGetUserData = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<WrenVM> vm,
);

typedef _c_wrenSetUserData = ffi.Void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Void> userData,
);

typedef _dart_wrenSetUserData = void Function(
  ffi.Pointer<WrenVM> vm,
  ffi.Pointer<ffi.Void> userData,
);

typedef WrenLoadModuleCompleteFn = ffi.Void Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
  WrenLoadModuleResult,
);

typedef WrenForeignMethodFn = ffi.Void Function(
  ffi.Pointer<WrenVM>,
);

typedef WrenFinalizerFn = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);

typedef WrenReallocateFn = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void>,
  ffi.Uint64,
  ffi.Pointer<ffi.Void>,
);

typedef WrenResolveModuleFn = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
  ffi.Pointer<ffi.Int8>,
);

typedef WrenLoadModuleFn = WrenLoadModuleResult Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
);

typedef WrenBindForeignMethodFn
    = ffi.Pointer<ffi.NativeFunction<WrenForeignMethodFn>> Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
  ffi.Pointer<ffi.Int8>,
  ffi.Uint8,
  ffi.Pointer<ffi.Int8>,
);

typedef WrenBindForeignClassFn = WrenForeignClassMethods Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
  ffi.Pointer<ffi.Int8>,
);

typedef WrenWriteFn = ffi.Void Function(
  ffi.Pointer<WrenVM>,
  ffi.Pointer<ffi.Int8>,
);

typedef WrenErrorFn = ffi.Void Function(
  ffi.Pointer<WrenVM>,
  ffi.Int32,
  ffi.Pointer<ffi.Int8>,
  ffi.Int32,
  ffi.Pointer<ffi.Int8>,
);
